import { z } from "zod";
import { zColor } from "@remotion/zod-types";

export const distressTransitionSchema = z.object({
  mode: z
    .enum([
      "dryBrush",
      "tonerScrape",
      "crtSnow",
      "trackingRoll",
      "signalTear",
      "dustBurn",
    ])
    .default("dryBrush"),
  primaryColor: zColor().default("#e9e7df"),
  secondaryColor: zColor().default("#777975"),
  accentColor: zColor().default("#ffffff"),
  coverColor: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/, "Use an opaque six-digit hex color")
    .default("#08090b"),
  direction: z.enum(["right", "left"]).default("right"),
  density: z.number().min(0.5).max(2).default(1),
  grainSize: z.number().min(0.6).max(8).default(1.5),
  roughness: z.number().min(0).max(1).default(0.75),
  noiseHoldFrames: z.number().int().min(1).max(4).default(1),
  seed: z.number().int().min(0).max(9999).default(37),
  durationFrames: z.number().int().min(24).max(120).default(42),
});
export type DistressTransitionProps = z.infer<typeof distressTransitionSchema>;
export const distressTransitionDurationFrames = 42;
export const defaultDistressTransitionProps = {
  mode: "dryBrush",
  primaryColor: "#e9e7df",
  secondaryColor: "#777975",
  accentColor: "#ffffff",
  coverColor: "#08090b",
  direction: "right",
  density: 1,
  grainSize: 1.5,
  roughness: 0.75,
  noiseHoldFrames: 1,
  seed: 37,
  durationFrames: distressTransitionDurationFrames,
} as const;

export const distressTransitionPatterns: Record<
  string,
  DistressTransitionProps
> = {
  dryBrushMono: {
    ...defaultDistressTransitionProps,
    mode: "dryBrush",
    primaryColor: "#e9e7df",
    secondaryColor: "#777975",
    accentColor: "#ffffff",
    grainSize: 2.4,
    durationFrames: 42,
    seed: 37,
    direction: "right",
  },
  dryBrushCyan: {
    ...defaultDistressTransitionProps,
    mode: "dryBrush",
    primaryColor: "#39e7ff",
    secondaryColor: "#7956e8",
    accentColor: "#dcffff",
    grainSize: 2.4,
    durationFrames: 42,
    seed: 54,
    direction: "left",
  },
  dryBrushAmber: {
    ...defaultDistressTransitionProps,
    mode: "dryBrush",
    primaryColor: "#ffb13b",
    secondaryColor: "#d74d2a",
    accentColor: "#fff3ce",
    grainSize: 2.4,
    durationFrames: 42,
    seed: 71,
    direction: "right",
  },
  tonerScrapeMono: {
    ...defaultDistressTransitionProps,
    mode: "tonerScrape",
    primaryColor: "#e9e7df",
    secondaryColor: "#777975",
    accentColor: "#ffffff",
    grainSize: 3.5,
    durationFrames: 48,
    seed: 138,
    direction: "right",
  },
  tonerScrapeCyan: {
    ...defaultDistressTransitionProps,
    mode: "tonerScrape",
    primaryColor: "#39e7ff",
    secondaryColor: "#7956e8",
    accentColor: "#dcffff",
    grainSize: 3.5,
    durationFrames: 48,
    seed: 155,
    direction: "left",
  },
  tonerScrapeAmber: {
    ...defaultDistressTransitionProps,
    mode: "tonerScrape",
    primaryColor: "#ffb13b",
    secondaryColor: "#d74d2a",
    accentColor: "#fff3ce",
    grainSize: 3.5,
    durationFrames: 48,
    seed: 172,
    direction: "right",
  },
  crtSnowMono: {
    ...defaultDistressTransitionProps,
    mode: "crtSnow",
    primaryColor: "#e9e7df",
    secondaryColor: "#777975",
    accentColor: "#ffffff",
    grainSize: 0.8,
    durationFrames: 36,
    seed: 239,
    direction: "right",
  },
  crtSnowCyan: {
    ...defaultDistressTransitionProps,
    mode: "crtSnow",
    primaryColor: "#39e7ff",
    secondaryColor: "#7956e8",
    accentColor: "#dcffff",
    grainSize: 0.8,
    durationFrames: 36,
    seed: 256,
    direction: "left",
  },
  crtSnowAmber: {
    ...defaultDistressTransitionProps,
    mode: "crtSnow",
    primaryColor: "#ffb13b",
    secondaryColor: "#d74d2a",
    accentColor: "#fff3ce",
    grainSize: 0.8,
    durationFrames: 36,
    seed: 273,
    direction: "right",
  },
  trackingRollMono: {
    ...defaultDistressTransitionProps,
    mode: "trackingRoll",
    primaryColor: "#e9e7df",
    secondaryColor: "#777975",
    accentColor: "#ffffff",
    grainSize: 1.2,
    durationFrames: 48,
    seed: 340,
    direction: "right",
  },
  trackingRollCyan: {
    ...defaultDistressTransitionProps,
    mode: "trackingRoll",
    primaryColor: "#39e7ff",
    secondaryColor: "#7956e8",
    accentColor: "#dcffff",
    grainSize: 1.2,
    durationFrames: 48,
    seed: 357,
    direction: "left",
  },
  trackingRollAmber: {
    ...defaultDistressTransitionProps,
    mode: "trackingRoll",
    primaryColor: "#ffb13b",
    secondaryColor: "#d74d2a",
    accentColor: "#fff3ce",
    grainSize: 1.2,
    durationFrames: 48,
    seed: 374,
    direction: "right",
  },
  signalTearMono: {
    ...defaultDistressTransitionProps,
    mode: "signalTear",
    primaryColor: "#e9e7df",
    secondaryColor: "#777975",
    accentColor: "#ffffff",
    grainSize: 1.8,
    durationFrames: 30,
    seed: 441,
    direction: "right",
  },
  signalTearCyan: {
    ...defaultDistressTransitionProps,
    mode: "signalTear",
    primaryColor: "#39e7ff",
    secondaryColor: "#7956e8",
    accentColor: "#dcffff",
    grainSize: 1.8,
    durationFrames: 30,
    seed: 458,
    direction: "left",
  },
  signalTearAmber: {
    ...defaultDistressTransitionProps,
    mode: "signalTear",
    primaryColor: "#ffb13b",
    secondaryColor: "#d74d2a",
    accentColor: "#fff3ce",
    grainSize: 1.8,
    durationFrames: 30,
    seed: 475,
    direction: "right",
  },
  dustBurnMono: {
    ...defaultDistressTransitionProps,
    mode: "dustBurn",
    primaryColor: "#e9e7df",
    secondaryColor: "#777975",
    accentColor: "#ffffff",
    grainSize: 2,
    durationFrames: 54,
    seed: 542,
    direction: "right",
  },
  dustBurnCyan: {
    ...defaultDistressTransitionProps,
    mode: "dustBurn",
    primaryColor: "#39e7ff",
    secondaryColor: "#7956e8",
    accentColor: "#dcffff",
    grainSize: 2,
    durationFrames: 54,
    seed: 559,
    direction: "left",
  },
  dustBurnAmber: {
    ...defaultDistressTransitionProps,
    mode: "dustBurn",
    primaryColor: "#ffb13b",
    secondaryColor: "#d74d2a",
    accentColor: "#fff3ce",
    grainSize: 2,
    durationFrames: 54,
    seed: 576,
    direction: "right",
  },
};
